/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from './contact';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/template_ref';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from 'ionic-angular/components/nav/nav-controller';
import * as import11 from '@angular/core/src/linker/component_factory';
const styles_ContactPage:any[] = [];
var renderType_ContactPage:import0.RenderComponentType = null;
class _View_ContactPage0 extends import1.AppView<import2.ContactPage> {
  _text_0:any;
  _anchor_1:any;
  private _appEl_1:import3.AppElement;
  _TemplateRef_1_4:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ContactPage0,renderType_ContactPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,null);
    this._appEl_1 = new import3.AppElement(1,null,this,this._anchor_1);
    this._TemplateRef_1_4 = new import8.TemplateRef_(this._appEl_1,viewFactory_ContactPage1);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n  ',null);
    this._el_3 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',null);
    this._el_5 = this.renderer.createElement(this._el_3,'ion-list',null);
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',null);
    this._el_7 = this.renderer.createElement(this._el_5,'ion-list-header',null);
    this._text_8 = this.renderer.createText(this._el_7,'Follow us on Twitter',null);
    this._text_9 = this.renderer.createText(this._el_5,'\n      ',null);
    this._el_10 = this.renderer.createElement(this._el_5,'ion-item',null);
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',null);
    this._el_12 = this.renderer.createElement(this._el_10,'ion-icon',null);
    this.renderer.setElementAttribute(this._el_12,'item-left','');
    this.renderer.setElementAttribute(this._el_12,'name','ionic');
    this._text_13 = this.renderer.createText(this._el_10,'\n        @ionicframework\n      ',null);
    this._text_14 = this.renderer.createText(this._el_5,'\n    ',null);
    this._text_15 = this.renderer.createText(this._el_3,'\n  ',null);
    this._text_16 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this.init([],[
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_4; }
    return notFoundResult;
  }
}
export function viewFactory_ContactPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import2.ContactPage> {
  if ((renderType_ContactPage === null)) { (renderType_ContactPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/tree-shake-ionic2/typescript-only-es2015-jsnext-ionic/src/app/pages/contact/contact.ts class ContactPage - inline template',0,import9.ViewEncapsulation.None,styles_ContactPage)); }
  return new _View_ContactPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ContactPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ContactPage1,renderType_ContactPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement(null,'ion-navbar',null);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'ion-title',null);
    this._text_3 = this.renderer.createText(this._el_2,'\n      Contact\n    ',null);
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',null);
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return null;
  }
}
function viewFactory_ContactPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ContactPage1(viewUtils,parentInjector,declarationEl);
}
const styles_ContactPage_Host:any[] = [];
var renderType_ContactPage_Host:import0.RenderComponentType = null;
class _View_ContactPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  private _appEl_0:import3.AppElement;
  _ContactPage_0_4:import2.ContactPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ContactPage_Host0,renderType_ContactPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('undefined',rootSelector,null);
    this._appEl_0 = new import3.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_ContactPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ContactPage_0_4 = new import2.ContactPage(this.parentInjector.get(import10.NavController));
    this._appEl_0.initComponent(this._ContactPage_0_4,[],compView_0);
    compView_0.create(this._ContactPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import2.ContactPage) && (0 === requestNodeIndex))) { return this._ContactPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ContactPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ContactPage_Host === null)) { (renderType_ContactPage_Host = viewUtils.createRenderComponentType('',0,null,styles_ContactPage_Host)); }
  return new _View_ContactPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ContactPageNgFactory:import11.ComponentFactory<import2.ContactPage> = new import11.ComponentFactory<import2.ContactPage>(null,viewFactory_ContactPage_Host0,import2.ContactPage);