/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from './home';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/template_ref';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from 'ionic-angular/components/nav/nav-controller';
import * as import11 from '@angular/core/src/linker/component_factory';
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = null;
class _View_HomePage0 extends import1.AppView<import2.HomePage> {
  _text_0:any;
  _anchor_1:any;
  private _appEl_1:import3.AppElement;
  _TemplateRef_1_4:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this._anchor_1 = this.renderer.createTemplateAnchor(parentRenderNode,null);
    this._appEl_1 = new import3.AppElement(1,null,this,this._anchor_1);
    this._TemplateRef_1_4 = new import8.TemplateRef_(this._appEl_1,viewFactory_HomePage1);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n  ',null);
    this._el_3 = this.renderer.createElement(parentRenderNode,'ion-content',null);
    this.renderer.setElementAttribute(this._el_3,'class','home');
    this.renderer.setElementAttribute(this._el_3,'padding','');
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',null);
    this._el_5 = this.renderer.createElement(this._el_3,'h2',null);
    this._text_6 = this.renderer.createText(this._el_5,'Welcome to Ionic!',null);
    this._text_7 = this.renderer.createText(this._el_3,'\n    ',null);
    this._el_8 = this.renderer.createElement(this._el_3,'p',null);
    this._text_9 = this.renderer.createText(this._el_8,'\n      This starter project comes with simple tabs-based layout for apps\n      that are going to primarily use a Tabbed UI.\n    ',null);
    this._text_10 = this.renderer.createText(this._el_3,'\n    ',null);
    this._el_11 = this.renderer.createElement(this._el_3,'p',null);
    this._text_12 = this.renderer.createText(this._el_11,'\n      Take a look at the ',null);
    this._el_13 = this.renderer.createElement(this._el_11,'code',null);
    this._text_14 = this.renderer.createText(this._el_13,'app/',null);
    this._text_15 = this.renderer.createText(this._el_11,' directory to add or change tabs,\n      update any existing page or create new pages.\n    ',null);
    this._text_16 = this.renderer.createText(this._el_3,'\n  ',null);
    this._text_17 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this.init([],[
      this._text_0,
      this._anchor_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.TemplateRef) && (1 === requestNodeIndex))) { return this._TemplateRef_1_4; }
    return notFoundResult;
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import2.HomePage> {
  if ((renderType_HomePage === null)) { (renderType_HomePage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/tree-shake-ionic2/typescript-only-es2015-jsnext-ionic/src/app/pages/home/home.ts class HomePage - inline template',0,import9.ViewEncapsulation.None,styles_HomePage)); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement(null,'ion-navbar',null);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',null);
    this._el_2 = this.renderer.createElement(this._el_0,'ion-title',null);
    this._text_3 = this.renderer.createText(this._el_2,'Home',null);
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',null);
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return null;
  }
}
function viewFactory_HomePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}
const styles_HomePage_Host:any[] = [];
var renderType_HomePage_Host:import0.RenderComponentType = null;
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  private _appEl_0:import3.AppElement;
  _HomePage_0_4:import2.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('undefined',rootSelector,null);
    this._appEl_0 = new import3.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import2.HomePage(this.parentInjector.get(import10.NavController));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import2.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === null)) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,null,styles_HomePage_Host)); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import11.ComponentFactory<import2.HomePage> = new import11.ComponentFactory<import2.HomePage>(null,viewFactory_HomePage_Host0,import2.HomePage);