/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from './tabs';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from '@angular/core/src/linker/element';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
const styles_TabsPage:any[] = [];
var renderType_TabsPage:import0.RenderComponentType = null;
class _View_TabsPage0 extends import1.AppView<import2.TabsPage> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  private _expr_0:any;
  private _expr_1:any;
  private _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentInjector:import4.Injector,declarationEl:import5.AppElement) {
    super(_View_TabsPage0,renderType_TabsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-tabs',null);
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',null);
    this._el_3 = this.renderer.createElement(this._el_1,'ion-tab',null);
    this.renderer.setElementAttribute(this._el_3,'tabIcon','home');
    this.renderer.setElementAttribute(this._el_3,'tabTitle','Home');
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',null);
    this._el_5 = this.renderer.createElement(this._el_1,'ion-tab',null);
    this.renderer.setElementAttribute(this._el_5,'tabIcon','information-circle');
    this.renderer.setElementAttribute(this._el_5,'tabTitle','About');
    this._text_6 = this.renderer.createText(this._el_1,'\n    ',null);
    this._el_7 = this.renderer.createElement(this._el_1,'ion-tab',null);
    this.renderer.setElementAttribute(this._el_7,'tabIcon','contacts');
    this.renderer.setElementAttribute(this._el_7,'tabTitle','Contact');
    this._text_8 = this.renderer.createText(this._el_1,'\n  ',null);
    this._text_9 = this.renderer.createText(parentRenderNode,'\n  ',null);
    this._expr_0 = import7.uninitialized;
    this._expr_1 = import7.uninitialized;
    this._expr_2 = import7.uninitialized;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[],[]);
    return null;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.context.tab1Root;
    if (import3.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'root',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.tab2Root;
    if (import3.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_5,'root',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.tab3Root;
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_7,'root',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_TabsPage0(viewUtils:import3.ViewUtils,parentInjector:import4.Injector,declarationEl:import5.AppElement):import1.AppView<import2.TabsPage> {
  if ((renderType_TabsPage === null)) { (renderType_TabsPage = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/tree-shake-ionic2/typescript-only-es2015-jsnext-ionic/src/app/pages/tabs/tabs.ts class TabsPage - inline template',0,import8.ViewEncapsulation.None,styles_TabsPage)); }
  return new _View_TabsPage0(viewUtils,parentInjector,declarationEl);
}
const styles_TabsPage_Host:any[] = [];
var renderType_TabsPage_Host:import0.RenderComponentType = null;
class _View_TabsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  private _appEl_0:import5.AppElement;
  _TabsPage_0_4:import2.TabsPage;
  constructor(viewUtils:import3.ViewUtils,parentInjector:import4.Injector,declarationEl:import5.AppElement) {
    super(_View_TabsPage_Host0,renderType_TabsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import5.AppElement {
    this._el_0 = this.selectOrCreateHostElement('undefined',rootSelector,null);
    this._appEl_0 = new import5.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_TabsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TabsPage_0_4 = new import2.TabsPage();
    this._appEl_0.initComponent(this._TabsPage_0_4,[],compView_0);
    compView_0.create(this._TabsPage_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import2.TabsPage) && (0 === requestNodeIndex))) { return this._TabsPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_TabsPage_Host0(viewUtils:import3.ViewUtils,parentInjector:import4.Injector,declarationEl:import5.AppElement):import1.AppView<any> {
  if ((renderType_TabsPage_Host === null)) { (renderType_TabsPage_Host = viewUtils.createRenderComponentType('',0,null,styles_TabsPage_Host)); }
  return new _View_TabsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const TabsPageNgFactory:import9.ComponentFactory<import2.TabsPage> = new import9.ComponentFactory<import2.TabsPage>(null,viewFactory_TabsPage_Host0,import2.TabsPage);