/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from './app';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from 'ionic-angular/components/nav/nav';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ionic-angular/components/nav/nav.d.ngfactory';
import * as import10 from 'ionic-angular/components/nav/view-controller';
import * as import11 from 'ionic-angular/components/nav/nav-controller';
import * as import12 from 'ionic-angular/components/app/app';
import * as import13 from 'ionic-angular/config/config';
import * as import14 from 'ionic-angular/util/keyboard';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/core/src/zone/ng_zone';
import * as import17 from '@angular/core/src/linker/component_resolver';
import * as import18 from '@angular/core/src/metadata/view';
import * as import19 from 'ionic-angular/platform/platform';
import * as import20 from '@angular/core/src/linker/component_factory';
const styles_App:any[] = [];
var renderType_App:import0.RenderComponentType = null;
class _View_App0 extends import1.AppView<import2.App> {
  _el_0:any;
  private _appEl_0:import3.AppElement;
  _Nav_0_4:import4.Nav;
  private _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_App0,renderType_App,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-nav',null);
    this._appEl_0 = new import3.AppElement(0,null,this,this._el_0);
    var compView_0:any = import9.viewFactory_Nav0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Nav_0_4 = new import4.Nav(this.parentInjector.get(import10.ViewController,null),this.parentInjector.get(import11.NavController,null),this.parentInjector.get(import12.App),this.parentInjector.get(import13.Config),this.parentInjector.get(import14.Keyboard),new import15.ElementRef(this._el_0),this.parentInjector.get(import16.NgZone),this.renderer,this.parentInjector.get(import17.ComponentResolver));
    this._appEl_0.initComponent(this._Nav_0_4,[],compView_0);
    compView_0.create(this._Nav_0_4,[],null);
    this._expr_0 = import8.uninitialized;
    this.init([],[this._el_0],[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.Nav) && (0 === requestNodeIndex))) { return this._Nav_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.rootPage;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Nav_0_4.root = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.cdState === import8.ChangeDetectorState.NeverChecked)) { this._Nav_0_4.ngAfterViewInit(); } }
  }
}
export function viewFactory_App0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import2.App> {
  if ((renderType_App === null)) { (renderType_App = viewUtils.createRenderComponentType('/Users/joshthomas/Workspace/tree-shake-ionic2/typescript-only-es2015-jsnext-ionic/src/app/app.ts class App - inline template',0,import18.ViewEncapsulation.None,styles_App)); }
  return new _View_App0(viewUtils,parentInjector,declarationEl);
}
const styles_App_Host:any[] = [];
var renderType_App_Host:import0.RenderComponentType = null;
class _View_App_Host0 extends import1.AppView<any> {
  _el_0:any;
  private _appEl_0:import3.AppElement;
  _App_0_4:import2.App;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_App_Host0,renderType_App_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectionStrategy.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ion-app',rootSelector,null);
    this._appEl_0 = new import3.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_App0(this.viewUtils,this.injector(0),this._appEl_0);
    this._App_0_4 = new import2.App(this.parentInjector.get(import19.Platform));
    this._appEl_0.initComponent(this._App_0_4,[],compView_0);
    compView_0.create(this._App_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import2.App) && (0 === requestNodeIndex))) { return this._App_0_4; }
    return notFoundResult;
  }
}
function viewFactory_App_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_App_Host === null)) { (renderType_App_Host = viewUtils.createRenderComponentType('',0,null,styles_App_Host)); }
  return new _View_App_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppNgFactory:import20.ComponentFactory<import2.App> = new import20.ComponentFactory<import2.App>('ion-app',viewFactory_App_Host0,import2.App);